name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Self-hosted runner ka use karne ke liye update

    steps:
    - name: SSH into Server and Execute Commands
      run: |
        ssh srvadmin@10.100.150.13 << 'EOF'
          cd ~
          ls -la
          # Clone repo if not exists, else pull latest changes
          if [ -d "repo" ]; then
            cd repo && git pull
          else
            git clone https://github.com/salmanjamil433/etms.git repo
            cd repo
          fi

          # Run Docker Compose (REMOVED the incorrect `-v` flag)
          docker compose up -d --build
        EOF
