name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Self-hosted runner ka use karne ke liye update

    steps:
    - name: Remove existing Docker packages
      run: |
        for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
          sudo apt-get remove -y $pkg
        done
        echo "Existing Docker packages removed."

    - name: Install Docker using official script
      run: |
        curl -fsSL https://get.docker.com | sh
        echo "Docker installed successfully."

    - name: Add user to Docker group
      run: |
        sudo usermod -aG docker $USER
        echo "User added to Docker group."

    - name: Verify Docker Installation
      run: docker --version

    - uses: actions/checkout@v4

    - name: Clone the repository and navigate
      run: |
        git clone https://github.com/salmanjamil433/etms.git repo
        cd repo

    - name: Run Docker Compose
      run: |
        ls -la
        docker compose up -d --build
